#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Run teammate models using the feature package generated by src.feature_pipeline."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "model_integration"
PROCESSED_DIR = PROJECT_ROOT / "outputs" / "processed"
OPTUNA_DIR = PROJECT_ROOT / "outputs" / "optuna"

sys.path.insert(0, str(PROJECT_ROOT))

from src.feature_pipeline import get_xy, load_feature_package  # noqa: E402
from modeling.evaluation import (  # noqa: E402
    build_comparison_table,
    inverse_transform_target,
    make_residual_plot,
    plot_actual_vs_predicted,
    plot_model_comparison,
)
from modeling.models import train_all_models  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--top-k", nargs="+", type=int, default=[5, 10, 14, 85])
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu"])
    parser.add_argument("--skip-plots", action="store_true")
    return parser.parse_args()


def load_recommended_features(top_k: int) -> List[str]:
    path = OPTUNA_DIR / f"recommended_top{top_k}_features.csv"
    if path.exists():
        return pd.read_csv(path)["feature"].tolist()

    # Some notebook experiments ask for extra comparison dimensions such as
    # top5/top10 even when Optuna's formal recommendation set is top11/top14/top85.
    # In that case, derive the feature subset from the saved RF ranking instead
    # of stopping the whole model-integration run.
    ranking_path = OPTUNA_DIR / "ranked_features_rf.csv"
    if not ranking_path.exists():
        raise FileNotFoundError(
            f"Missing feature list: {path}, and fallback ranking is also missing: {ranking_path}. "
            "Run scripts/run_feature_pipeline.py first."
        )
    ranking = pd.read_csv(ranking_path)
    if "feature" not in ranking.columns:
        raise ValueError(f"Fallback ranking file has no 'feature' column: {ranking_path}")
    if top_k < 1 or top_k > len(ranking):
        raise ValueError(f"top_k={top_k} is outside the available feature range 1..{len(ranking)}")

    selected = ranking.head(top_k).copy()
    selected.to_csv(path, index=False, encoding="utf-8-sig")
    print(f"[Model] generated fallback feature list for top{top_k}: {path}")
    return selected["feature"].tolist()


def scale_target(y_train_raw: np.ndarray, y_val_raw: np.ndarray, y_test_raw: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, float, float]:
    mean = float(np.mean(y_train_raw))
    std = float(np.std(y_train_raw))
    if std == 0:
        raise ValueError("Training target standard deviation is zero.")
    return (
        ((y_train_raw - mean) / std).astype(np.float32),
        ((y_val_raw - mean) / std).astype(np.float32),
        ((y_test_raw - mean) / std).astype(np.float32),
        mean,
        std,
    )


def save_best_plots(results: Dict[str, Dict[str, object]], best_name: str, y_test: np.ndarray, dates: pd.DatetimeIndex, target_mean: float, target_std: float, fig_dir: Path) -> None:
    info = results[best_name]
    pred = np.asarray(info["test_pred"]).flatten()
    yt = np.asarray(info.get("_y_test", y_test)).flatten()
    plot_dates = dates
    if "_y_test" in info:
        offset = len(y_test) - len(yt)
        plot_dates = dates[offset:]
    n = min(len(yt), len(pred), len(plot_dates))
    y_true_raw = inverse_transform_target(yt[:n], target_mean, target_std)
    y_pred_raw = inverse_transform_target(pred[:n], target_mean, target_std)
    plot_actual_vs_predicted(plot_dates[:n], y_true_raw, y_pred_raw, best_name, str(fig_dir / f"actual_vs_predicted_{best_name}.png"))
    make_residual_plot(yt[:n], pred[:n], best_name, str(fig_dir / f"residual_{best_name}.png"), target_mean=target_mean, target_std=target_std, dates=plot_dates[:n])


def run_one_dimension(top_k: int, package: Dict[str, object], device: str, skip_plots: bool) -> Tuple[pd.DataFrame, Dict[str, object]]:
    features = load_recommended_features(top_k)
    split_dir = OUTPUT_DIR / f"top{top_k}"
    result_dir = split_dir / "results"
    fig_dir = split_dir / "figures"
    result_dir.mkdir(parents=True, exist_ok=True)
    fig_dir.mkdir(parents=True, exist_ok=True)

    X_train, y_train_raw = get_xy(package["train"], features)
    X_val, y_val_raw = get_xy(package["val"], features)
    X_test, y_test_raw = get_xy(package["test"], features)
    y_train, y_val, y_test, target_mean, target_std = scale_target(y_train_raw, y_val_raw, y_test_raw)

    print("\n" + "=" * 80)
    print(f"[Model] top{top_k}: X_train={X_train.shape}, X_val={X_val.shape}, X_test={X_test.shape}, device={device}")
    print("=" * 80)
    results = train_all_models(X_train, y_train, X_val, y_val, X_test, y_test, device=device)
    comparison = build_comparison_table(results, y_test, target_mean, target_std)
    comparison.insert(0, "top_k", top_k)
    comparison.insert(1, "feature_count", len(features))
    comparison.to_csv(result_dir / f"model_comparison_top{top_k}.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame({"feature": features}).to_csv(result_dir / f"features_top{top_k}.csv", index=False, encoding="utf-8-sig")
    with open(result_dir / "target_scaler_info.json", "w", encoding="utf-8") as f:
        json.dump({"target_mean_AQI_train": target_mean, "target_std_AQI_train": target_std}, f, ensure_ascii=False, indent=2)

    best = comparison.sort_values("RMSE_AQI").iloc[0].to_dict()
    if not skip_plots:
        plot_model_comparison(
            comparison,
            str(fig_dir / f"model_comparison_top{top_k}.png"),
            title=f"接入我的特征工程 top{top_k} 后的模型表现对比",
        )
        save_best_plots(results, str(best["Model"]), y_test, package["test"].index, target_mean, target_std, fig_dir)
    print(f"[Model] top{top_k} best={best['Model']} RMSE={best['RMSE_AQI']:.4f} MAE={best['MAE_AQI']:.4f} R2={best['R2']:.4f}")
    return comparison, best


def write_summary(all_tables: List[pd.DataFrame], best_rows: List[Dict[str, object]]) -> None:
    result_dir = OUTPUT_DIR / "results"
    result_dir.mkdir(parents=True, exist_ok=True)
    all_results = pd.concat(all_tables, ignore_index=True)
    all_results.to_csv(result_dir / "all_model_comparison_my_features.csv", index=False, encoding="utf-8-sig")
    best_df = pd.DataFrame(best_rows).sort_values("RMSE_AQI")
    best_df.to_csv(result_dir / "best_by_dimension.csv", index=False, encoding="utf-8-sig")
    readme = [
        "# Model integration results",
        "",
        "## Best by recommended dimension",
        "",
        best_df[["top_k", "Model", "Type", "RMSE_AQI", "MAE_AQI", "R2", "N_Test"]].to_markdown(index=False),
    ]
    (OUTPUT_DIR / "README.md").write_text("\n".join(readme), encoding="utf-8")


def main() -> None:
    args = parse_args()
    if args.device == "cuda":
        try:
            import torch
            if not torch.cuda.is_available():
                print("[Model] CUDA requested but unavailable; falling back to CPU.")
                args.device = "cpu"
        except Exception:
            print("[Model] PyTorch CUDA check failed; falling back to CPU.")
            args.device = "cpu"

    package = load_feature_package(PROCESSED_DIR)
    all_tables: List[pd.DataFrame] = []
    best_rows: List[Dict[str, object]] = []
    for top_k in args.top_k:
        table, best = run_one_dimension(top_k, package, args.device, args.skip_plots)
        all_tables.append(table)
        best_rows.append(best)
    write_summary(all_tables, best_rows)
    print(f"\n[Model] integration outputs: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
